#!/usr/bin/env python

import os
import pathlib
import json

spool = pathlib.Path('./out_spool')

config = json.loads(os.environ['MAUTIC_CONFIG_PARAMETERS'])

mailer_spool_path = config.get('mailer_spool_path')
if not mailer_spool_path:
    raise Exception('Spool path not found in env')

directory = pathlib.Path(mailer_spool_path)
if not directory.is_dir():
    raise Exception('Provided directory does not exists')

for message in directory.glob('*.message'):
    message.rename(spool.joinpath(message.name))
